CREATE DATABASE faculdade;

USE faculdade;

SHOW TABLES;
DESCRIBE Student;
DESCRIBE Adm;

CREATE TABLE Student(
ra INT AUTO_INCREMENT,
nome VARCHAR(30) NOT NULL,
endereco VARCHAR(60),
celular CHAR(14),
email VARCHAR(50),
curso VARCHAR(60),
PRIMARY KEY(ra)
);

SELECT * FROM Student;

CREATE TABLE Adm(
cpf CHAR(12) NOT NULL, 
nome VARCHAR(50) NOT NULL, 
email VARCHAR(60) NOT NULL, 
pass_word VARCHAR(70) NOT NULL, 
celular CHAR(14),
PRIMARY KEY(cpf)
);

SELECT * FROM Adm;